name: Alexa Shopping List Sync
version: '2602.054.23'
slug: alexa_shopping_list
description: Alexa Shopping List synchronisation server
url: "https://github.com/raidolo/home-assistant-alexa-shopping-list"
arch:
  - aarch64
  - amd64
image: "raidolo/ha-alexa-shopping-list-sync"
startup: "services"
ports:
  4000/tcp: 4000
map:
  - type: addon_config
    read_only: false
    path: /config
